[workspace]
members = [
    "examples"
]

[workspace.profile.release]
opt-level = 3

[package]
name = "blocksense-fhe-oracle"
version = "0.1.0"
edition = "2021"

[dependencies]

[[test]]
name = "quantization_test"
path = "tests/quantization_test.rs"

[profile.release]
opt-level = 3
